const products = [
  {
    id: 'harbinger-contract-coastal-oak',
    slug: 'harbinger-contract-coastal-oak',
    sku: 'HARB-CONTRACT-COASTALOAK', // Harbinger SKU for inventory tracking
    name: 'Harbinger Contract Series – Coastal Oak',
    brand: 'Harbinger',
    collection: 'Contract Series',
    type: 'Luxury Vinyl Plank',
    colourName: 'Coastal Oak',
    installation: 'Glue-down',
    useType: 'Light commercial & residential',
    dimensionsIn: {
      width: 6,
      length: 48,
    },
    thicknessMm: 2.0,
    wearLayerMm: 0.3, // 12 mil wear layer
    wearLayerMil: 12,
    edge: 'Micro-bevel',
    construction: 'High-pressure heat laminated',
    coating: 'Harbinger 4S coating',
    waterproof: true,
    radiantHeatCompatible: true,
    texture: 'Realistic embossed texture showing grain and knots',
    coverageSqFtPerBox: 48,
    warrantyResidential: 'Lifetime limited residential warranty',
    warrantyCommercial: '20-year light commercial warranty',
    boxesPerSkid: 84,
    pricePerSqFt: 4.99, // weekly deal price
    compareAtPricePerSqFt: 6.49, // regular price
    currency: 'CAD',
    image: '/images/optimized/harbinger-coastal-oak-hero.webp',
    swatchImage: '/images/products/contract-coastal-oak-swatch.jpg',
    badge: 'Contract Series · Glue-down',
    shortTagline: 'Durable, stylish glue-down vinyl at contractor pricing.',
    description: 'Harbinger Contract Series - Coastal Oak is a commercial-grade glue-down luxury vinyl plank with a realistic embossed oak texture. Built for busy homes and light commercial spaces, it delivers waterproof performance, scratch resistance, and easy maintenance. The 2.0 mm profile with a 12-mil wear layer keeps it durable and stable for kitchens, basements, rentals, and high-traffic areas.',
    warranty: 'Lifetime limited residential warranty / 20-year light commercial warranty',
    // Legacy fields for backward compatibility
    thickness: 2.0, // mm
    wearLayer: 12, // mil
    // Calculate price from pricePerSqFt for backward compatibility
    price: Math.round(4.99 * 48 * 100), // $239.52 = 23952 cents
    isWeeklyDeal: true,
    compareAtPrice: Math.round(6.49 * 48 * 100), // $311.52 = 31152 cents
    upsellSkus: [
      'uzin_ke_2000_s',
      'uzin_kr_430',
      'uzin_ke_66',
      'price_underlay_001',
      'harbinger-reducer',
      'harbinger-t-moulding',
      'harbinger-flush-overlap-nosing',
      'harbinger-sac-square-nosing',
    ],
    rating: {
      count: 127,
      rate: 4.8,
    },
    highlights: [
      'Durable, stylish and low-maintenance glue-down vinyl at contractor pricing.',
      '100% waterproof luxury vinyl plank suitable for kitchens, basements and rentals.',
      'High-pressure heat laminated construction with Harbinger 4S coating for superior durability, scratch, stain and scuff resistance.',
      'Realistic embossed texture with visible grain and knots for a true wood look.',
      'Suitable for all interior floor surfaces above, on or below grade.',
      'Lifetime limited residential finish warranty and 20-year commercial warranty.',
    ],
    // Story-driven marketing content for Deal of the Week
    dealContent: {
      theVibe: "Coastal Oak brings an easy, modern feel to your space — soft grey undertones with warm oak grain that works whether you're renovating a 1970s split-level or finishing a brand-new basement suite. It's the kind of floor that looks good in photos but doesn't scream \"look at me\" when you walk in the room.",
      whyPeopleChooseIt: [
        "The colour hides dust, pet hair, and everyday mess better than most light floors — a real plus if you're not into daily sweeping.",
        "Glue-down install means no hollow sounds underfoot, and it stays flat even with temperature swings.",
        "Commercial-grade construction at residential pricing — this is the same spec contractors use in medical clinics and busy retail.",
        "The embossed texture actually feels like wood grain, not plastic."
      ],
      goodToKnow: [
        "Glue-down requires a smooth, clean subfloor. Concrete slabs need to be flat within 3mm over 3m and fully cured (at least 60 days for new pours). Plywood works great; particle board does not.",
        "You'll need adhesive — we recommend UZIN KE 2000 S for most installs, or KR 430 for high-moisture areas like laundry rooms.",
        "Direct sunlight through large windows can warm any floor — consider window film if you have south-facing glass walls."
      ],
      perfectFor: [
        "Basement suites and rentals",
        "Kitchens and laundry rooms",
        "Home offices and dens",
        "Light commercial (waiting rooms, small retail)",
        "Homes with kids or pets"
      ],
      specsAtAGlance: [
        { label: "Thickness", value: "2.0 mm" },
        { label: "Wear Layer", value: "12 mil (0.3 mm)" },
        { label: "Plank Size", value: '6" × 48"' },
        { label: "Coverage", value: "48 sq ft/box" },
        { label: "Edge", value: "Micro-bevel" },
        { label: "Install", value: "Glue-down" },
        { label: "Waterproof", value: "Yes, 100%" },
        { label: "Radiant Heat", value: "Compatible" },
        { label: "Warranty", value: "Lifetime residential / 20-year commercial" }
      ],
      howVfoMakesItEasy: [
        "Local pickup in Victoria — no waiting weeks for shipping from the mainland.",
        "Questions? Call or email us. We'll help you figure out how much you need, which adhesive to use, and whether your subfloor is ready.",
        "All boxes from the same production batch, so your colour matches wall to wall."
      ]
    },
  },
  {
    id: 'uzin_ke_2000_s',
    slug: 'uzin-ke-2000-s-adhesive',
    name: 'UZIN KE 2000 S - Universal Adhesive (1 Gallon)',
    brand: 'UZIN',
    type: 'Accessory',
    subType: 'Adhesive',
    price: 8999, // $89.99 per gallon
    currency: 'CAD',
    image: '/images/uzin-ke-2000-s.png',
    datasheetUrl: '/resources/Uzin%20Ke%202000s.pdf',
    description: 'Universal adhesive for common floor coverings including vinyl, LVT/LVP, carpet tile, carpet with common backings, rubber sheet/tile, linoleum, and VCT. Designed for porous and non-porous substrates with fast drying and low odor for occupied buildings.',
    shortTagline: 'Universal adhesive for vinyl, LVT/LVP, and carpet.',
    chooseThisIf: 'Standard residential installs or when you need a universal adhesive that also works with carpet tile and common carpet backings.',
    bestFor: ['Most residential projects', 'Vinyl, LVT/LVP, and carpet tile', 'Porous and non-porous substrates', 'Quick installations'],
    isWeeklyDeal: false,
    compareAtPrice: null,
    upsellSkus: [],
    coverage: {
      sqFtPerUnit: 150, // Conservative middle estimate (between 75-210 range)
      buffer: 1.0, // No buffer - exact coverage
      recommendedFor: ['Luxury Vinyl Plank', 'Laminate'], // Flooring types this adhesive works with
    },
    rating: {
      count: 45,
      rate: 4.8,
    },
    highlights: [
      'Universal wet and pressure sensitive adhesive',
      'Covers 75-210 sq ft per gallon (depending on application method and flooring type)',
      'Short waiting time for faster installation',
      'Excellent application properties',
      'Good grab with stringing for easy positioning',
      'Suitable for all common resilient coverings, textile coverings, and wall coverings',
      'Compatible with UZIN insulation/installation underlays',
      'Professional-grade dispersion adhesive',
    ],
    specifications: {
      size: '1 Gallon (3.78 L)',
      coverage: '75-210 sq ft per gallon (varies by application method and flooring type)',
      waitingTime: '24-72 hours before walking on floor',
      applicationMethod: 'Trowel application',
      temperature: 'Best used at room temperature (60-77°F)',
      shelfLife: '12 months when stored properly',
    },
  },
  {
    id: 'uzin_kr_430',
    slug: 'uzin-kr-430-adhesive',
    name: 'UZIN KR 430 - 2-Component PU Adhesive (10 kg)',
    brand: 'UZIN',
    type: 'Accessory',
    subType: 'Adhesive',
    price: 24999, // $249.99 per 10 kg kit
    currency: 'CAD',
    image: '/images/uzin-kr-430.png',
    datasheetUrl: '/resources/Uzin%20KR%20430.pdf',
    description: '2-component polyurethane adhesive for demanding installations and extreme conditions. Suitable for LVT/LVP, PVC, rubber sheet, linoleum tile, rubber tiles, rubber granulate backed coverings, and sports flooring with strong resistance to plasticizers, surface moisture, and temperature exposure.',
    shortTagline: 'Heavy-duty 2-component adhesive for extreme use.',
    chooseThisIf: 'Heavy-duty residential or commercial installs, rolling loads, exterior/interior use, or moisture-prone areas.',
    bestFor: ['LVT/LVP, PVC, rubber sheet/tile', 'Linoleum tile and sports flooring', 'Rolling loads and high moisture', 'Extreme temperature exposure'],
    isWeeklyDeal: false,
    compareAtPrice: null,
    upsellSkus: [],
    coverage: {
      sqFtPerUnit: 200, // Approximately 200 sq ft per 10 kg kit
      buffer: 1.0,
      recommendedFor: ['Luxury Vinyl Plank', 'Laminate'],
    },
    rating: {
      count: 28,
      rate: 4.9,
    },
    highlights: [
      '2-component polyurethane adhesive for maximum bond strength',
      'Covers approximately 200 sq ft per 10 kg kit',
      'Extremely high final strength and hardness',
      'Excellent resistance to plasticizers and moisture',
      'Temperature resistant for heated/cooled environments',
      'Ideal for rolling loads and heavy equipment',
      'Professional-grade for demanding commercial installs',
      'Requires mixing before application',
    ],
    specifications: {
      size: '10 kg (2-component kit)',
      coverage: 'Approximately 200 sq ft per kit',
      cureTime: '24-48 hours for full cure',
      applicationMethod: 'Trowel application after mixing components',
      temperature: 'Can withstand temperature extremes after curing',
      shelfLife: '12 months unopened',
      mixRatio: 'Follow manufacturer instructions for component mixing',
    },
  },
  {
    id: 'uzin_ke_66',
    slug: 'uzin-ke-66-adhesive',
    name: 'UZIN KE 66 - Fiber-Reinforced Adhesive (1 Gallon)',
    brand: 'UZIN',
    type: 'Accessory',
    subType: 'Adhesive',
    price: 10999, // $109.99 per gallon
    currency: 'CAD',
    image: '/images/uzin-ke-66.png',
    datasheetUrl: '/resources/Uzin%20KE%2066.pdf',
    description: 'Fiber-reinforced, hard-setting wet set adhesive for vinyl and rubber flooring on porous substrates. Designed for high shear strength with resistance to indentations and shrinkage, ideal for occupied buildings.',
    shortTagline: 'Fiber-reinforced adhesive for vinyl and rubber.',
    chooseThisIf: 'High-traffic residential or commercial spaces on porous substrates (concrete, plywood) with vinyl or rubber flooring.',
    bestFor: ['Vinyl sheet/tile and LVT/LVP', 'Rubber sheet/tile up to 3/16"', 'Porous substrates only', 'High-traffic areas'],
    isWeeklyDeal: false,
    compareAtPrice: null,
    upsellSkus: [],
    coverage: {
      sqFtPerUnit: 150, // Approximately 150 sq ft per gallon
      buffer: 1.0,
      recommendedFor: ['Luxury Vinyl Plank', 'Laminate'],
    },
    rating: {
      count: 34,
      rate: 4.7,
    },
    highlights: [
      'Fiber-reinforced for extra strength and durability',
      'Covers approximately 100-150 sq ft per gallon',
      'High shear strength resists movement',
      'Excellent resistance to indentations',
      'Prevents shrinkage over time',
      'Ideal for rolling loads and furniture',
      'Wet set application for strong initial grab',
      'Best on porous substrates like concrete and plywood',
    ],
    specifications: {
      size: '1 Gallon (3.78 L)',
      coverage: '100-150 sq ft per gallon',
      setTime: 'Wet set application',
      applicationMethod: 'Trowel application',
      temperature: 'Best used at room temperature (60-77°F)',
      shelfLife: '12 months when stored properly',
      substrateRequirement: 'Porous substrates recommended',
    },
  },
  {
    id: 'price_underlay_001',
    slug: 'quietwalk-plus-underlayment',
    name: 'QuietWalk PLUS Premium Underlayment - 360 sq ft Roll',
    brand: 'QuietWalk',
    type: 'Accessory',
    subType: 'Underlayment',
    price: 12999, // $129.99 - typical price for 360 sq ft roll
    currency: 'CAD',
    image: '/images/underlayment-optimized.jpg',
    description: 'Premium 360 sq ft underlayment roll with DriWick Technology for hardwood, laminate, engineered wood, and bamboo floors. It includes a moisture-managing vapor barrier, reduces noise transmission, and smooths minor subfloor imperfections. Ideal for glue-down or floating installs where added comfort and sound control are important.',
    shortTagline: 'Premium acoustic underlayment with moisture protection.',
    coverageSqFtPerBox: 360,
    isWeeklyDeal: false,
    compareAtPrice: null,
    upsellSkus: [],
    rating: {
      count: 156,
      rate: 4.7,
    },
    highlights: [
      'Covers 360 sq ft - Roll Size: 60 ft x 6 ft x 1/8 in',
      'DriWick Technology wicks away subfloor moisture while protecting flooring materials',
      'Antimicrobial treated recycled fibers for moisture protection',
      'Superior noise reduction - absorbs sound and keeps it from traveling to other rooms',
      'Performance upgrade over poly foams - economical alternative to rubber and cork',
      'Vapor barrier specially formulated to accept glue-down installations',
      'Use with hardwood, laminate, engineered wood, and bamboo',
      'Compatible with both glue-down and floating applications',
      'NOT for luxury vinyl plank - see QuietWalk Luxury Vinyl for LVP',
    ],
    specifications: {
      model: 'QW360PLUS',
      sku: '1001755087',
      rollSize: '60 ft x 6 ft x 1/8 in',
      packageSize: '73 in x 13 in x 13 in',
      coverage: '360 sq ft per roll',
      thickness: '1/8 inch',
      applications: 'Glue-down and floating installations',
      compatibleWith: 'Hardwood, laminate, engineered wood, bamboo',
      notCompatibleWith: 'Luxury vinyl plank (use QuietWalk Luxury Vinyl instead)',
    },
  },
  {
    id: 'harbinger-reducer',
    slug: 'harbinger-reducer',
    name: 'Harbinger Reducer',
    brand: 'Harbinger',
    type: 'Accessory',
    subType: 'Trim',
    price: 5500, // $55 per 7ft piece
    currency: 'CAD',
    image: '/images/reducer.jpg',
    description: 'Colour-matched reducer transition for Harbinger flooring. Used to smoothly reduce height where your flooring meets a lower surface.',
    shortTagline: 'Colour-matched reducer for clean transitions.',
    useWhen: 'Your flooring meets a lower surface like carpet, tile, or an exterior door threshold.',
    appearanceNote: 'Colour matched to the flooring ordered. Photo shows the profile/shape only.',
    lengthFt: 7, // 2400mm = ~7ft per piece
    alwaysRecommend: true,
    recommendedFor: ['Luxury Vinyl Plank'],
    isWeeklyDeal: false,
    compareAtPrice: null,
    upsellSkus: [],
    highlights: [
      'Only available with the purchase of Harbinger products',
      'Size: 2400mm x 45mm x 7.5mm (94.5” x 1.75” x 0.3”)',
      'T-Mouldings & Reducers include deep or shallow track to match product thickness',
    ],
    specifications: {
      length: '2400mm (94.5")',
      width: '45mm (1.75")',
      thickness: '7.5mm (0.3")',
      availability: 'Only with Harbinger flooring purchase',
    },
  },
  {
    id: 'harbinger-t-moulding',
    slug: 'harbinger-t-moulding',
    name: 'Harbinger T-Moulding',
    brand: 'Harbinger',
    type: 'Accessory',
    subType: 'Trim',
    price: 5500, // $55 per 7ft piece
    currency: 'CAD',
    image: '/images/t-molding-optimized.jpg',
    description: 'Colour-matched T-moulding for transitions between two floors of the same height.',
    shortTagline: 'Clean transitions between equal-height floors.',
    useWhen: 'Two floors of the same height meet in a doorway or at an expansion joint.',
    appearanceNote: 'Colour matched to the flooring ordered. Photo shows the profile/shape only.',
    lengthFt: 7, // 2400mm = ~7ft per piece
    alwaysRecommend: true,
    recommendedFor: ['Luxury Vinyl Plank'],
    isWeeklyDeal: false,
    compareAtPrice: null,
    upsellSkus: [],
    highlights: [
      'Only available with the purchase of Harbinger products',
      'Size: 2400mm x 45mm x 2.5mm (94.5” x 1.75” x 0.125”)',
      'T-Mouldings & Reducers include deep or shallow track to match product thickness',
    ],
    specifications: {
      length: '2400mm (94.5")',
      width: '45mm (1.75")',
      thickness: '2.5mm (0.125")',
      availability: 'Only with Harbinger flooring purchase',
    },
  },
  {
    id: 'harbinger-flush-overlap-nosing',
    slug: 'harbinger-flush-nosing',
    name: 'Harbinger Flush Nosing',
    brand: 'Harbinger',
    type: 'Accessory',
    subType: 'Trim',
    price: 5500, // $55 per 7ft piece
    currency: 'CAD',
    image: '/resources/Flushnosing.png',
    description: 'Flush stair/edge nosing that finishes exposed edges with a clean, low-profile lip.',
    shortTagline: 'Flush nosing for a clean, low-profile edge.',
    useWhen: 'You want a flush stair nosing profile for exposed edges and step-downs.',
    appearanceNote: 'Colour matched to the flooring ordered. Photo shows the profile/shape only.',
    lengthFt: 7, // 2400mm = ~7ft per piece
    stepsPerPiece: 3, // One 7ft piece covers approximately 3 stair steps
    alwaysRecommend: true,
    recommendedFor: ['Luxury Vinyl Plank'],
    isWeeklyDeal: false,
    compareAtPrice: null,
    upsellSkus: [],
    highlights: [
      'Only available with the purchase of Harbinger products',
      'Size: 2400mm x 50mm x 3mm (94.5” x 1.9” x 0.125”)',
    ],
    specifications: {
      length: '2400mm (94.5")',
      width: '50mm (1.9")',
      thickness: '3mm (0.125")',
      availability: 'Only with Harbinger flooring purchase',
    },
  },
  {
    id: 'harbinger-sac-square-nosing',
    slug: 'harbinger-overlap-nosing',
    name: 'Harbinger Overlap Nosing',
    brand: 'Harbinger',
    type: 'Accessory',
    subType: 'Trim',
    price: 5500, // $55 per 7ft piece
    currency: 'CAD',
    image: '/resources/OverlapNosing.png',
    description: 'Overlap stair nosing profile that provides a more pronounced lip for finished stair edges.',
    shortTagline: 'Overlap nosing for a finished stair edge.',
    useWhen: 'You want an overlap nosing profile for stair edges and step-downs.',
    appearanceNote: 'Colour matched to the flooring ordered. Photo shows the profile/shape only.',
    lengthFt: 7, // 2400mm = ~7ft per piece
    stepsPerPiece: 3, // One 7ft piece covers approximately 3 stair steps
    alwaysRecommend: true,
    recommendedFor: ['Luxury Vinyl Plank'],
    isWeeklyDeal: false,
    compareAtPrice: null,
    upsellSkus: [],
    highlights: [
      'Only available with the purchase of Harbinger products',
      'Size: 2400mm x 82mm x 35mm (94.5” x 3.25” x 1.4”)',
    ],
    specifications: {
      length: '2400mm (94.5")',
      width: '82mm (3.25")',
      thickness: '35mm (1.4")',
      availability: 'Only with Harbinger flooring purchase',
    },
  },
];

export default products;
