/**
 * Product Description Generator
 * Generates 3 variants (A, B, C) per product, tests them, and picks winners
 */

const fs = require('fs');
const path = require('path');

// Parse CSV data
const csvData = `id,vendor,series,name,slug,description,series_description
1,Harbinger,Contract,Bonsai Maple,harbinger-contract-bonsai-maple,"A warm maple tone with subtle grain variation that brings organic warmth to modern interiors. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Commercial-grade glue-down vinyl at contractor pricing, built for heavy-traffic installs with 4S scratch/stain/scuff protection."
2,Harbinger,Contract,Brisbane,harbinger-contract-brisbane,"A sun-bleached coastal wood look with soft grey undertones for relaxed, beachy appeal. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Commercial-grade glue-down vinyl at contractor pricing, built for heavy-traffic installs with 4S scratch/stain/scuff protection."
3,Harbinger,Contract,Cairns,harbinger-contract-cairns,"A weathered driftwood aesthetic with cool grey tones that evoke coastal tranquility. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Commercial-grade glue-down vinyl at contractor pricing, built for heavy-traffic installs with 4S scratch/stain/scuff protection."
4,Harbinger,Contract,Canberra,harbinger-contract-canberra,"A light sandy wood look with clean lines and a contemporary neutral finish. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Commercial-grade glue-down vinyl at contractor pricing, built for heavy-traffic installs with 4S scratch/stain/scuff protection."
5,Harbinger,Contract,Coventry Spice,harbinger-contract-coventry-spice,"A rich spiced wood tone with warm amber undertones that add depth to any room. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Commercial-grade glue-down vinyl at contractor pricing, built for heavy-traffic installs with 4S scratch/stain/scuff protection."
6,Harbinger,Contract,Marla,harbinger-contract-marla,"A balanced mid-tone wood look with natural grain character and timeless appeal. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Commercial-grade glue-down vinyl at contractor pricing, built for heavy-traffic installs with 4S scratch/stain/scuff protection."
7,Harbinger,Contract,Melbourne,harbinger-contract-melbourne,"A soft greige wood look that bridges warm and cool palettes with effortless versatility. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Commercial-grade glue-down vinyl at contractor pricing, built for heavy-traffic installs with 4S scratch/stain/scuff protection."
8,Harbinger,Contract,Perth,harbinger-contract-perth,"A pale ash-inspired plank with subtle silver undertones for a light, airy feel. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Commercial-grade glue-down vinyl at contractor pricing, built for heavy-traffic installs with 4S scratch/stain/scuff protection."
9,Harbinger,Contract,Savannah Oak,harbinger-contract-savannah-oak,"A classic honey oak with gentle grain movement and inviting warmth. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Commercial-grade glue-down vinyl at contractor pricing, built for heavy-traffic installs with 4S scratch/stain/scuff protection."
10,Harbinger,Contract,Sienna,harbinger-contract-sienna,"A rich terracotta-toned wood with rustic character and earthy warmth. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Commercial-grade glue-down vinyl at contractor pricing, built for heavy-traffic installs with 4S scratch/stain/scuff protection."
11,Harbinger,Contract,Sydney,harbinger-contract-sydney,"A sophisticated grey-brown wood look with refined grain detail for modern spaces. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Commercial-grade glue-down vinyl at contractor pricing, built for heavy-traffic installs with 4S scratch/stain/scuff protection."
12,Harbinger,Contract,Tumbleweed,harbinger-contract-tumbleweed,"A warm taupe wood tone with natural variation that complements both rustic and modern decor. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Commercial-grade glue-down vinyl at contractor pricing, built for heavy-traffic installs with 4S scratch/stain/scuff protection."
13,Harbinger,Contract,Winton,harbinger-contract-winton,"A soft wheat-toned wood look with gentle grain for bright, welcoming interiors. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Commercial-grade glue-down vinyl at contractor pricing, built for heavy-traffic installs with 4S scratch/stain/scuff protection."
165,Harbinger,Contract Series,Coventry Spice,harbinger-contract-series-coventry-spice,"A rich spiced wood tone with warm amber undertones that add depth to any room. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Durable, stylish and low maintenance glue down vinyl at contractor pricing."
166,Harbinger,Contract Series,Savannah Oak,harbinger-contract-series-savannah-oak,"A classic honey oak with gentle grain movement and inviting warmth. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Durable, stylish and low maintenance glue down vinyl at contractor pricing."
167,Harbinger,Contract Series,Bonsai Maple,harbinger-contract-series-bonsai-maple,"A warm maple tone with subtle grain variation that brings organic warmth to modern interiors. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Durable, stylish and low maintenance glue down vinyl at contractor pricing."
168,Harbinger,Contract Series,Tumbleweed,harbinger-contract-series-tumbleweed,"A warm taupe wood tone with natural variation that complements both rustic and modern decor. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Durable, stylish and low maintenance glue down vinyl at contractor pricing."
169,Harbinger,Contract Series,Sienna,harbinger-contract-series-sienna,"A rich terracotta-toned wood with rustic character and earthy warmth. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Durable, stylish and low maintenance glue down vinyl at contractor pricing."
170,Harbinger,Contract Series,Melbourne,harbinger-contract-series-melbourne,"A soft greige wood look that bridges warm and cool palettes with effortless versatility. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Durable, stylish and low maintenance glue down vinyl at contractor pricing."
171,Harbinger,Contract Series,Canberra,harbinger-contract-series-canberra,"A light sandy wood look with clean lines and a contemporary neutral finish. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Durable, stylish and low maintenance glue down vinyl at contractor pricing."
172,Harbinger,Contract Series,Perth,harbinger-contract-series-perth,"A pale ash-inspired plank with subtle silver undertones for a light, airy feel. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Durable, stylish and low maintenance glue down vinyl at contractor pricing."
173,Harbinger,Contract Series,Winton,harbinger-contract-series-winton,"A soft wheat-toned wood look with gentle grain for bright, welcoming interiors. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Durable, stylish and low maintenance glue down vinyl at contractor pricing."
174,Harbinger,Contract Series,Sydney,harbinger-contract-series-sydney,"A sophisticated grey-brown wood look with refined grain detail for modern spaces. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Durable, stylish and low maintenance glue down vinyl at contractor pricing."
175,Harbinger,Contract Series,Marla,harbinger-contract-series-marla,"A balanced mid-tone wood look with natural grain character and timeless appeal. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Durable, stylish and low maintenance glue down vinyl at contractor pricing."
176,Harbinger,Contract Series,Cairns,harbinger-contract-series-cairns,"A weathered driftwood aesthetic with cool grey tones that evoke coastal tranquility. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Durable, stylish and low maintenance glue down vinyl at contractor pricing."
177,Harbinger,Contract Series,Brisbane,harbinger-contract-series-brisbane,"A sun-bleached coastal wood look with soft grey undertones for relaxed, beachy appeal. Commercial-grade glue-down vinyl with 4S coating for scratch, stain, and scuff resistance in high-traffic spaces.","Durable, stylish and low maintenance glue down vinyl at contractor pricing."
14,Harbinger,Craftsman,Angola,harbinger-craftsman-angola,"A warm sandstone tile look with natural veining for understated elegance. Large-format 16×32"" tile with 0.55mm wear layer and 4S coating for durable, design-forward floors.","Design-forward visuals with durable glue-down performance — available in wide planks and large-format stone tiles."
15,Harbinger,Craftsman,Bali,harbinger-craftsman-bali,"An exotic wood look with tropical warmth and rich, varied grain patterns. Wide 9.33×72"" plank with 0.55mm wear layer and 4S coating for durable, design-forward floors.","Design-forward visuals with durable glue-down performance — available in wide planks and large-format stone tiles."
16,Harbinger,Craftsman,Beachcomber,harbinger-craftsman-beachcomber,"A sun-washed coastal wood look with pale blonde tones and relaxed charm. Wide plank format with 0.55mm wear layer and 4S coating for durable, design-forward floors.","Design-forward visuals with durable glue-down performance — available in wide planks and large-format stone tiles."
17,Harbinger,Craftsman,Botswana,harbinger-craftsman-botswana,"A rich slate-inspired tile with dark grey depth and natural stone character. Large-format 16×32"" tile with 0.55mm wear layer and 4S coating for durable, design-forward floors.","Design-forward visuals with durable glue-down performance — available in wide planks and large-format stone tiles."
18,Harbinger,Craftsman,Brunei,harbinger-craftsman-brunei,"A deep espresso wood look with bold grain and sophisticated warmth. Wide 9.33×60"" plank with 0.55mm wear layer and 4S coating for durable, design-forward floors.","Design-forward visuals with durable glue-down performance — available in wide planks and large-format stone tiles."
19,Harbinger,Craftsman,Burmese Teak,harbinger-craftsman-burmese-teak,"A rich golden teak with exotic grain movement and timeless luxury appeal. Wide 9×48"" plank with 0.55mm wear layer and 4S coating for durable, design-forward floors.","Design-forward visuals with durable glue-down performance — available in wide planks and large-format stone tiles."
20,Harbinger,Craftsman,Farmhouse Nordic,harbinger-craftsman-farmhouse-nordic,"A whitewashed Scandinavian wood look with clean lines and bright, airy appeal. Wide 9×48"" plank with 0.55mm wear layer and 4S coating for durable, design-forward floors.","Design-forward visuals with durable glue-down performance — available in wide planks and large-format stone tiles."
21,Harbinger,Craftsman,Farmhouse Umber,harbinger-craftsman-farmhouse-umber,"A deep umber wood tone with rustic character and cozy farmhouse warmth. Wide 9×48"" plank with 0.55mm wear layer and 4S coating for durable, design-forward floors.","Design-forward visuals with durable glue-down performance — available in wide planks and large-format stone tiles."
22,Harbinger,Craftsman,Gobi,harbinger-craftsman-gobi,"A desert-inspired neutral wood look with soft sandy tones and subtle grain. Wide plank format with 0.55mm wear layer and 4S coating for durable, design-forward floors.","Design-forward visuals with durable glue-down performance — available in wide planks and large-format stone tiles."
23,Harbinger,Craftsman,Horizon,harbinger-craftsman-horizon,"A soft grey-brown wood look with smooth grain and calming, contemporary appeal. Wide plank format with 0.55mm wear layer and 4S coating for durable, design-forward floors.","Design-forward visuals with durable glue-down performance — available in wide planks and large-format stone tiles."
24,Harbinger,Craftsman,Jakarta,harbinger-craftsman-jakarta,"A warm chestnut wood look with deep grain character and inviting richness. Extra-wide 9.33×72"" plank with 0.55mm wear layer and 4S coating for durable, design-forward floors.","Design-forward visuals with durable glue-down performance — available in wide planks and large-format stone tiles."
25,Harbinger,Craftsman,Kenya,harbinger-craftsman-kenya,"A warm travertine-inspired tile with honey tones and natural stone texture. Large-format 16×32"" tile with 0.55mm wear layer and 4S coating for durable, design-forward floors.","Design-forward visuals with durable glue-down performance — available in wide planks and large-format stone tiles."
26,Harbinger,Craftsman,Madagascar,harbinger-craftsman-madagascar,"A cool grey stone tile with subtle veining and modern minimalist appeal. Large-format 16×32"" tile with 0.55mm wear layer and 4S coating for durable, design-forward floors.","Design-forward visuals with durable glue-down performance — available in wide planks and large-format stone tiles."
27,Harbinger,Craftsman,Namibia,harbinger-craftsman-namibia,"A desert sandstone tile with warm beige tones and organic texture. Large-format 16×32"" tile with 0.55mm wear layer and 4S coating for durable, design-forward floors.","Design-forward visuals with durable glue-down performance — available in wide planks and large-format stone tiles."
28,Harbinger,Craftsman,Paris,harbinger-craftsman-paris,"A refined grey oak look with European elegance and timeless sophistication. Wide 9.33×60"" plank with 0.55mm wear layer and 4S coating for durable, design-forward floors.","Design-forward visuals with durable glue-down performance — available in wide planks and large-format stone tiles."
29,Harbinger,Craftsman,Tanzania,harbinger-craftsman-tanzania,"A rich charcoal stone tile with dramatic depth and bold contemporary style. Large-format 16×32"" tile with 0.55mm wear layer and 4S coating for durable, design-forward floors.","Design-forward visuals with durable glue-down performance — available in wide planks and large-format stone tiles."
30,Harbinger,Craftsman,Terrazzo,harbinger-craftsman-terrazzo,"A classic terrazzo pattern with scattered aggregate for retro-modern charm. Large-format 16×32"" tile with 0.55mm wear layer and 4S coating for durable, design-forward floors.","Design-forward visuals with durable glue-down performance — available in wide planks and large-format stone tiles."
31,Harbinger,Craftsman,Tonga,harbinger-craftsman-tonga,"A warm walnut wood look with rich chocolate tones and classic grain pattern. Wide 9.33×60"" plank with 0.55mm wear layer and 4S coating for durable, design-forward floors.","Design-forward visuals with durable glue-down performance — available in wide planks and large-format stone tiles."
32,Harbinger,Craftsman,Topeka,harbinger-craftsman-topeka,"A mid-tone oak look with balanced warmth and versatile, everyday appeal. Wide plank format with 0.55mm wear layer and 4S coating for durable, design-forward floors.","Design-forward visuals with durable glue-down performance — available in wide planks and large-format stone tiles."
33,Harbinger,Craftsman,Zambia,harbinger-craftsman-zambia,"A deep slate tile with charcoal depth and bold, sophisticated presence. Large-format 16×32"" tile with 0.55mm wear layer and 4S coating for durable, design-forward floors.","Design-forward visuals with durable glue-down performance — available in wide planks and large-format stone tiles."
178,Harbinger,Craftsman Series,Beachcomber,harbinger-craftsman-series-beachcomber,"Where style, design, performance and price come together in harmony.","Where style, design, performance and price come together in harmony."
179,Harbinger,Craftsman Series,Topeka,harbinger-craftsman-series-topeka,"Where style, design, performance and price come together in harmony.","Where style, design, performance and price come together in harmony."
180,Harbinger,Craftsman Series,Horizon,harbinger-craftsman-series-horizon,"Where style, design, performance and price come together in harmony.","Where style, design, performance and price come together in harmony."
181,Harbinger,Craftsman Series,Gobi,harbinger-craftsman-series-gobi,"Where style, design, performance and price come together in harmony.","Where style, design, performance and price come together in harmony."
182,Harbinger,Craftsman Series,Farmhouse Umber,harbinger-craftsman-series-farmhouse-umber,"Where style, design, performance and price come together in harmony.","Where style, design, performance and price come together in harmony."
183,Harbinger,Craftsman Series,Farmhouse Nordic,harbinger-craftsman-series-farmhouse-nordic,"Where style, design, performance and price come together in harmony.","Where style, design, performance and price come together in harmony."
184,Harbinger,Craftsman Series,Burmese Teak,harbinger-craftsman-series-burmese-teak,"Where style, design, performance and price come together in harmony.","Where style, design, performance and price come together in harmony."
185,Harbinger,Craftsman Series,Terrazzo,harbinger-craftsman-series-terrazzo,"Where style, design, performance and price come together in harmony.","Where style, design, performance and price come together in harmony."
186,Harbinger,Craftsman Series,Namibia,harbinger-craftsman-series-namibia,"Where style, design, performance and price come together in harmony.","Where style, design, performance and price come together in harmony."
187,Harbinger,Craftsman Series,Zambia,harbinger-craftsman-series-zambia,"Where style, design, performance and price come together in harmony.","Where style, design, performance and price come together in harmony."
188,Harbinger,Craftsman Series,Madagascar,harbinger-craftsman-series-madagascar,"Where style, design, performance and price come together in harmony.","Where style, design, performance and price come together in harmony."
189,Harbinger,Craftsman Series,Angola,harbinger-craftsman-series-angola,"Where style, design, performance and price come together in harmony.","Where style, design, performance and price come together in harmony."
190,Harbinger,Craftsman Series,Botswana,harbinger-craftsman-series-botswana,"Where style, design, performance and price come together in harmony.","Where style, design, performance and price come together in harmony."
191,Harbinger,Craftsman Series,Kenya,harbinger-craftsman-series-kenya,"Where style, design, performance and price come together in harmony.","Where style, design, performance and price come together in harmony."
192,Harbinger,Craftsman Series,Tanzania,harbinger-craftsman-series-tanzania,"Where style, design, performance and price come together in harmony.","Where style, design, performance and price come together in harmony."
193,Harbinger,Craftsman Series,Brunei,harbinger-craftsman-series-brunei,"Where style, design, performance and price come together in harmony.","Where style, design, performance and price come together in harmony."
194,Harbinger,Craftsman Series,Jakarta,harbinger-craftsman-series-jakarta,"Where style, design, performance and price come together in harmony.","Where style, design, performance and price come together in harmony."
195,Harbinger,Craftsman Series,Tonga,harbinger-craftsman-series-tonga,"Where style, design, performance and price come together in harmony.","Where style, design, performance and price come together in harmony."
196,Harbinger,Craftsman Series,Bali,harbinger-craftsman-series-bali,"Where style, design, performance and price come together in harmony.","Where style, design, performance and price come together in harmony."
197,Harbinger,Craftsman Series,Paris,harbinger-craftsman-series-paris,"Where style, design, performance and price come together in harmony.","Where style, design, performance and price come together in harmony."
34,Harbinger,Essentials,Beach House,harbinger-essentials-beach-house,"A light coastal wood look with sun-bleached character and casual elegance. Heavy-commercial glue-down vinyl with 0.55mm wear layer and 4S coating for easy, low-maintenance care.","Clean, neutral palette in a versatile glue-down build — straightforward durability for any space."
35,Harbinger,Essentials,Hampton Greige,harbinger-essentials-hampton-greige,"A sophisticated greige wood tone that balances warm and cool for effortless coordination. Heavy-commercial glue-down vinyl with 0.55mm wear layer and 4S coating for easy, low-maintenance care.","Clean, neutral palette in a versatile glue-down build — straightforward durability for any space."
36,Harbinger,Essentials,Perissa,harbinger-essentials-perissa,"A soft grey stone tile with understated elegance and Mediterranean warmth. Heavy-commercial glue-down vinyl with 0.55mm wear layer and 4S coating for easy, low-maintenance care.","Clean, neutral palette in a versatile glue-down build — straightforward durability for any space."
37,Harbinger,Harbinger Acoustic Click,Carrara,harbinger-harbinger-acoustic-click-carrara,,"Rigid composite core with cork backing delivers stability, sound reduction, and a refined upscale finish."
38,Harbinger,Signature Acoustic Click,Aberdeen,harbinger-signature-acoustic-click-aberdeen,"A weathered grey oak with subtle grain movement and relaxed highland charm. Floating click install with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
39,Harbinger,Signature Acoustic Click,Alexandria,harbinger-signature-acoustic-click-alexandria,"A warm honey oak with classic grain and inviting, sunlit appeal. Extra-wide 9×72"" floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
40,Harbinger,Signature Acoustic Click,Amtico Grey,harbinger-signature-acoustic-click-amtico-grey,"A cool concrete-inspired tile with industrial edge and urban sophistication. Large-format floating click tile with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
41,Harbinger,Signature Acoustic Click,Bantame,harbinger-signature-acoustic-click-bantame,"A warm sandstone tile with soft, earthy texture and Mediterranean appeal. Large-format floating click tile with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
42,Harbinger,Signature Acoustic Click,Basalt,harbinger-signature-acoustic-click-basalt,"A dramatic dark basalt look with volcanic depth and bold, modern presence. Large-format floating click tile with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
43,Harbinger,Signature Acoustic Click,Birmingham,harbinger-signature-acoustic-click-birmingham,"A mid-tone oak with balanced warmth and refined English character. Floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
44,Harbinger,Signature Acoustic Click,Canterbury,harbinger-signature-acoustic-click-canterbury,"A rich walnut tone with deep grain character and traditional warmth. Extra-wide 9×72"" floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
45,Harbinger,Signature Acoustic Click,Cardiff,harbinger-signature-acoustic-click-cardiff,"A cool grey oak with subtle silver undertones and contemporary calm. Extra-wide 9×72"" floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
46,Harbinger,Signature Acoustic Click,Chester,harbinger-signature-acoustic-click-chester,"A dark espresso oak with bold grain and sophisticated depth. Floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
47,Harbinger,Signature Acoustic Click,Churchill,harbinger-signature-acoustic-click-churchill,"A distinguished grey-brown oak with stately character and timeless appeal. Floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
48,Harbinger,Signature Acoustic Click,Colchester,harbinger-signature-acoustic-click-colchester,"A warm chestnut wood look with inviting depth and natural grain variation. Extra-wide 9×72"" floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
49,Harbinger,Signature Acoustic Click,Cornwall,harbinger-signature-acoustic-click-cornwall,"A weathered coastal grey with driftwood character and seaside serenity. Extra-wide 9×72"" floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
50,Harbinger,Signature Acoustic Click,Derby,harbinger-signature-acoustic-click-derby,"A light ash wood look with soft grey tones and effortless modern style. Floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
51,Harbinger,Signature Acoustic Click,Dublin,harbinger-signature-acoustic-click-dublin,"A rich auburn oak with warm copper undertones and Celtic charm. Floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
52,Harbinger,Signature Acoustic Click,Durham,harbinger-signature-acoustic-click-durham,"A smoky charcoal oak with dramatic depth and urban sophistication. Floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
53,Harbinger,Signature Acoustic Click,Exeter,harbinger-signature-acoustic-click-exeter,"A soft taupe wood look with gentle warmth and understated elegance. Floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
54,Harbinger,Signature Acoustic Click,Gaudi,harbinger-signature-acoustic-click-gaudi,"An artistic terrazzo-inspired tile with playful pattern and creative flair. Large-format floating click tile with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
55,Harbinger,Signature Acoustic Click,Kaya,harbinger-signature-acoustic-click-kaya,"A soft limestone tile with warm ivory tones and natural elegance. Large-format floating click tile with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
56,Harbinger,Signature Acoustic Click,Knoxville,harbinger-signature-acoustic-click-knoxville,"A classic hickory look with bold grain movement and rustic warmth. Extra-wide 9×72"" floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
57,Harbinger,Signature Acoustic Click,Marengo Grey,harbinger-signature-acoustic-click-marengo-grey,"A smoky grey stone tile with subtle depth and refined contemporary style. Large-format floating click tile with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
58,Harbinger,Signature Acoustic Click,Marmo,harbinger-signature-acoustic-click-marmo,"A classic white marble look with elegant grey veining and timeless luxury. Large-format floating click tile with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
59,Harbinger,Signature Acoustic Click,Nero,harbinger-signature-acoustic-click-nero,"A bold black stone tile with dramatic impact and sleek modern edge. Large-format floating click tile with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
60,Harbinger,Signature Acoustic Click,Nottingham,harbinger-signature-acoustic-click-nottingham,"A warm caramel oak with rich tones and classic English appeal. Floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
61,Harbinger,Signature Acoustic Click,Plymouth,harbinger-signature-acoustic-click-plymouth,"A light sandy oak with coastal warmth and relaxed New England charm. Extra-wide 9×72"" floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
62,Harbinger,Signature Acoustic Click,Poole,harbinger-signature-acoustic-click-poole,"A soft greige oak that blends warm and cool for effortless versatility. Floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
63,Harbinger,Signature Acoustic Click,San Antonio,harbinger-signature-acoustic-click-san-antonio,"A warm pecan wood look with southwestern character and inviting warmth. Extra-wide 9×72"" floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
64,Harbinger,Signature Acoustic Click,Selene,harbinger-signature-acoustic-click-selene,"A soft lunar grey tile with ethereal calm and sophisticated serenity. Large-format floating click tile with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
65,Harbinger,Signature Acoustic Click,Sheffield,harbinger-signature-acoustic-click-sheffield,"A steel-grey oak with industrial edge and contemporary urban appeal. Floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
66,Harbinger,Signature Acoustic Click,St. Tropez Limestone,harbinger-signature-acoustic-click-st-tropez-limestone,"A creamy French limestone with Mediterranean warmth and coastal elegance. Large-format floating click tile with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
67,Harbinger,Signature Acoustic Click,Sussex,harbinger-signature-acoustic-click-sussex,"A warm honey wood look with gentle grain and inviting cottage appeal. Floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
68,Harbinger,Signature Acoustic Click,Truro,harbinger-signature-acoustic-click-truro,"A weathered grey-brown oak with coastal character and relaxed sophistication. Extra-wide 9×72"" floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
69,Harbinger,Signature Acoustic Click,York,harbinger-signature-acoustic-click-york,"A classic mid-tone oak with traditional grain and enduring appeal. Floating click plank with cork underlayment for sound control and a 0.55mm wear layer.","Floating click install with integrated cork underlayment for quiet comfort and realistic embossed texture."
70,Harbinger,The Quiet Zone,Amuse,harbinger-the-quiet-zone-amuse,"A warm beige stone tile with playful texture and inviting softness. IXPE acoustic backing for quieter rooms with a 0.55mm wear layer and stable glue-down install.","IXPE acoustic layer attached to LVT for quieter rooms, glue-down stability, and a soft feel underfoot."
71,Harbinger,The Quiet Zone,Bianco,harbinger-the-quiet-zone-bianco,"A bright white stone tile with clean, luminous appeal and modern freshness. IXPE acoustic backing for quieter rooms with a 0.55mm wear layer and stable glue-down install.","IXPE acoustic layer attached to LVT for quieter rooms, glue-down stability, and a soft feel underfoot."
72,Harbinger,The Quiet Zone,Cirrus,harbinger-the-quiet-zone-cirrus,"A soft grey wood look with wispy grain and cloud-like serenity. IXPE acoustic backing for quieter rooms with a 0.55mm wear layer and stable glue-down install.","IXPE acoustic layer attached to LVT for quieter rooms, glue-down stability, and a soft feel underfoot."
73,Harbinger,The Quiet Zone,Coastal Fog,harbinger-the-quiet-zone-coastal-fog,"A misty grey stone tile with soft coastal atmosphere and calming presence. IXPE acoustic backing for quieter rooms with a 0.55mm wear layer and stable glue-down install.","IXPE acoustic layer attached to LVT for quieter rooms, glue-down stability, and a soft feel underfoot."
74,Harbinger,The Quiet Zone,Copenhagen,harbinger-the-quiet-zone-copenhagen,"A pale Scandinavian wood look with minimalist beauty and Nordic calm. Wide 8×60"" plank with IXPE acoustic backing for quieter rooms and a 0.55mm wear layer.","IXPE acoustic layer attached to LVT for quieter rooms, glue-down stability, and a soft feel underfoot."
75,Harbinger,The Quiet Zone,Cumulus,harbinger-the-quiet-zone-cumulus,"A light grey wood look with soft, billowing grain and dreamy appeal. IXPE acoustic backing for quieter rooms with a 0.55mm wear layer and stable glue-down install.","IXPE acoustic layer attached to LVT for quieter rooms, glue-down stability, and a soft feel underfoot."
76,Harbinger,The Quiet Zone,Mountain Fog,harbinger-the-quiet-zone-mountain-fog,"A cool grey stone tile with alpine mist atmosphere and natural calm. IXPE acoustic backing for quieter rooms with a 0.55mm wear layer and stable glue-down install.","IXPE acoustic layer attached to LVT for quieter rooms, glue-down stability, and a soft feel underfoot."
77,Harbinger,The Quiet Zone,Munich,harbinger-the-quiet-zone-munich,"A warm European oak with refined grain and continental elegance. Wide 8×60"" plank with IXPE acoustic backing for quieter rooms and a 0.55mm wear layer.","IXPE acoustic layer attached to LVT for quieter rooms, glue-down stability, and a soft feel underfoot."
78,Harbinger,The Quiet Zone,Night Sky,harbinger-the-quiet-zone-night-sky,"A deep charcoal stone tile with dramatic depth and midnight sophistication. IXPE acoustic backing for quieter rooms with a 0.55mm wear layer and stable glue-down install.","IXPE acoustic layer attached to LVT for quieter rooms, glue-down stability, and a soft feel underfoot."
79,Harbinger,The Quiet Zone,Nimbus,harbinger-the-quiet-zone-nimbus,"A medium grey wood look with storm-cloud depth and moody elegance. IXPE acoustic backing for quieter rooms with a 0.55mm wear layer and stable glue-down install.","IXPE acoustic layer attached to LVT for quieter rooms, glue-down stability, and a soft feel underfoot."
80,Harbinger,The Quiet Zone,Sea Salt,harbinger-the-quiet-zone-sea-salt,"A pale coastal wood with sea-salt whitewash and breezy beach appeal. Wide 8×60"" plank with IXPE acoustic backing for quieter rooms and a 0.55mm wear layer.","IXPE acoustic layer attached to LVT for quieter rooms, glue-down stability, and a soft feel underfoot."
81,Harbinger,The Quiet Zone,Serene,harbinger-the-quiet-zone-serene,"A soft neutral wood look with gentle grain and peaceful, calming appeal. IXPE acoustic backing for quieter rooms with a 0.55mm wear layer and stable glue-down install.","IXPE acoustic layer attached to LVT for quieter rooms, glue-down stability, and a soft feel underfoot."
82,Harbinger,The Quiet Zone,Vik,harbinger-the-quiet-zone-vik,"A cool slate-grey tile with Icelandic character and minimalist edge. IXPE acoustic backing for quieter rooms with a 0.55mm wear layer and stable glue-down install.","IXPE acoustic layer attached to LVT for quieter rooms, glue-down stability, and a soft feel underfoot."`;

// Parse CSV
function parseCSV(csv) {
  const lines = csv.trim().split('\n');
  const headers = lines[0].split(',');
  
  return lines.slice(1).map(line => {
    const values = [];
    let current = '';
    let inQuotes = false;
    
    for (let i = 0; i < line.length; i++) {
      const char = line[i];
      
      if (char === '"') {
        inQuotes = !inQuotes;
      } else if (char === ',' && !inQuotes) {
        values.push(current.trim());
        current = '';
      } else {
        current += char;
      }
    }
    values.push(current.trim());
    
    const obj = {};
    headers.forEach((header, idx) => {
      obj[header] = values[idx] || '';
    });
    
    return obj;
  });
}

const products = parseCSV(csvData);

console.log(`Loaded ${products.length} products`);
console.log('Summary by series:');
const seriesCounts = products.reduce((acc, p) => {
  acc[p.series] = (acc[p.series] || 0) + 1;
  return acc;
}, {});
Object.entries(seriesCounts).forEach(([series, count]) => {
  console.log(`  ${series}: ${count} products`);
});

module.exports = { products, parseCSV };
